### PR TITLE
Create pages-en_GB.json

### PR DESCRIPTION
**Pull request by justinhartman**
Localised British English language file.

### CODE REVIEW

**Comment by justinhartman** [comment]
Sorry, I closed this PR by accident.

**Comment by AndiDittrich** [comment]
Hi Justin,
thanks for your contribution. would you like to change some phrases too ? it doesn't sounds very british imho ?!

br, Andi

**Comment by justinhartman** [comment]
I'd be more than happy to! I agree the phrasing could do with some changes. I just wasn't sure if I was allowed to go ahead and do it. I will get right on it!

**Comment by justinhartman** [comment]
PS: Forgive my typos in the comment above. Here I am, talking about changing text grammatically yet my comment is almost incoherent :-D
I was on the go when typing my response and my auto-correct really let me down.

**Pull request closed without merging**
