### PR TITLE
fixed

### PR DESCRIPTION
**Pull request by Rizwan-Hasan**

### CODE REVIEW

**Comment by AndiDittrich** [comment]
any comments / reasons / issues ?

**Comment by Rizwan-Hasan** [comment]
On default config of nginx, using the line internal after alias in ErrorPages location doesn't work. Removing the line internal works perfectly.

**Comment by AndiDittrich** [comment]
regarding the [nginx docs](http://nginx.org/en/docs/http/ngx_http_core_module.html#internal) the directive is correct for this specific scope `error_pages`

**Comment by Rizwan-Hasan** [comment]
But it didn't worked for me. I'm on Ubuntu 18.04 LTS VM on Microsoft Azure. Anyway, Thanks 😇

**Pull request closed without merging**
