### PR TITLE
Implemented internationalization

### PR DESCRIPTION
**Pull request by antunesleo**
Just implemented a simple Internationalization. For now, we have this available just for portuguese, but other people can translate this their languages.
The internacionalization will not broke the script, and to generate the pages in any language you just need to pass the **language** parameter on the url like this:

localhost:8080/generate.php?language=pt_BR 

if you open localhost:8080/generate.php the script will consider english (en_US) as default language.

### CODE REVIEW

**Comment by AndiDittrich** [comment]
Hi Leonardo,

thanks for your support! its a great enhancement :+1: 

The HttpErrorPages `generator.php` is designed as cli/console application. Therefore i have to modify your request to fetch the language identifier as cli argument. i hope this would be ok ?

best regards, Andi

**Comment by antunesleo** [comment]
Hi Andi,

I'm not much familiar with php and don't read this specific part of the
doc: 😂

> $ php generator.php


All this time i was opening the file on the embbed apache2 server. Feel
free to edit my commit and pass the language as a parameter on the console!



2017-08-23 4:08 GMT-03:00 Andi Dittrich <notifications@github.com>:

**Comment by antunesleo** [comment]
Just send another commit with the correction, now we can pass the language as an argument. If i understand the php argument correctly, I don't have a native way to pass something like this:

$ php generator.php --language pt_br

And, to use a second argument I have to enter the first one:

$ php generator.php config.ini pt_br

In this first moment I think that we do not need to do the argument interpreter, for example: "--language pt_br". But if we start developing another arguments, This tends to be bureaucratic.

any ideas?

**Comment by AndiDittrich** [comment]
Hi Leonardo,

thanks! for now this solution is convenient.

in case the project is going more complex i will replace the generator script with a new version written in **javascript** including [commanderjs](https://github.com/tj/commander.js/) to parse the cli args 😄 

best regards, Andi

**Pull request merged**
